# Generated by Django 2.1.7 on 2019-05-02 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticActiveSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freqs_with_tails_im_z', models.IntegerField(default=0)),
                ('freqs_with_negative_im_z', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='eisspectrum',
            name='filename',
            field=models.CharField(max_length=1000),
        ),
        migrations.AddField(
            model_name='eisspectrum',
            name='automatic_active_sample',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIS.AutomaticActiveSample'),
        ),
    ]
