# Generated by Django 2.1.7 on 2019-05-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIS', '0002_auto_20190502_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticactivesample',
            name='sample_count',
            field=models.IntegerField(default=0),
        ),
    ]
