# Generated by Django 2.1.7 on 2019-05-03 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIS', '0004_inversemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftScaleParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_alpha', models.FloatField(default=0)),
                ('w_alpha', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='eisspectrum',
            name='shift_scale_params',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIS.ShiftScaleParameters'),
        ),
    ]
