# Generated by Django 2.1.7 on 2019-05-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EIS', '0005_auto_20190503_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eisspectrum',
            old_name='shift_scale_params',
            new_name='shift_scale_parameters',
        ),
    ]
