# Generated by Django 2.1.7 on 2019-05-06 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIS', '0006_auto_20190503_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EIS.ImpedanceSample')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useless', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CircuitParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('value', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CircuitParameterSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FitSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_ang_freq', models.FloatField()),
                ('real_part', models.FloatField()),
                ('imag_part', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FitSpectrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InverseModelResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EIS.ActivitySetting')),
                ('circuit_parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EIS.CircuitParameterSet')),
                ('fit_spectrum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EIS.FitSpectrum')),
                ('inv_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EIS.InverseModel')),
                ('shift_scale_parameters', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EIS.ShiftScaleParameters')),
                ('spectrum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EIS.EISSpectrum')),
            ],
        ),
        migrations.AddField(
            model_name='fitsample',
            name='fit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EIS.FitSpectrum'),
        ),
        migrations.AddField(
            model_name='circuitparameter',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EIS.CircuitParameterSet'),
        ),
        migrations.AddField(
            model_name='activitysample',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EIS.ActivitySetting'),
        ),
    ]
