# Generated by Django 2.1.7 on 2019-05-08 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIS', '0007_auto_20190506_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinetuneResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_parameters', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EIS.CircuitParameterSet')),
                ('fit_spectrum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EIS.FitSpectrum')),
            ],
        ),
        migrations.RemoveField(
            model_name='eisspectrum',
            name='shift_scale_parameters',
        ),
        migrations.AlterField(
            model_name='inversemodelresult',
            name='activity_setting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EIS.ActivitySetting'),
        ),
        migrations.AlterField(
            model_name='inversemodelresult',
            name='circuit_parameters',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EIS.CircuitParameterSet'),
        ),
        migrations.AddField(
            model_name='finetuneresult',
            name='inv_model_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EIS.InverseModelResult'),
        ),
    ]
