# Generated by Django 2.1.7 on 2019-05-08 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIS', '0008_auto_20190508_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='finetuneresult',
            name='learning_rate',
            field=models.FloatField(default=0.001),
        ),
        migrations.AddField(
            model_name='finetuneresult',
            name='nll_coeff',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='finetuneresult',
            name='ordering_coeff',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='finetuneresult',
            name='sensible_phi_coeff',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='finetuneresult',
            name='simplicity_coeff',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='finetuneresult',
            name='inv_model_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EIS.InverseModelResult'),
        ),
    ]
